
const wasi =
{
	args_get: () => { return 0; },
	args_sizes_get: () => { return 0; },
	environ_get: () => { return 0; },
	environ_sizes_get: () => { return 0; },
	clock_res_get: () => { return 0; },
	clock_time_get: () => { return 0; },
	fd_advise: () => { return 0; },
	fd_allocate: () => { return 0; },
	fd_close: () => { return 0; },
	fd_datasync: () => { return 0; },
	fd_fdstat_get: () => { return 0; },
	fd_fdstat_set_flags: () => { return 0; },
	fd_fdstat_set_rights: () => { return 0; },
	fd_filestat_get: () => { return 0; },
	fd_filestat_set_size: () => { return 0; },
	fd_filestat_set_times: () => { return 0; },
	fd_pread: () => { return 0; },
	fd_prestat_get: () => { return 0; },
	fd_prestat_dir_name: () => { return 0; },
	fd_pwrite: () => { return 0; },
	fd_read: () => { return 0; },
	fd_readdir: () => { return 0; },
	fd_renumber: () => { return 0; },
	fd_seek: () => { return 0; },
	fd_sync: () => { return 0; },
	fd_tell: () => { return 0; },
	fd_write: () => { return 0; },
	path_create_directory: () => { return 0; },
	path_filestat_get: () => { return 0; },
	path_filestat_set_times: () => { return 0; },
	path_link: () => { return 0; },
	path_open: () => { return 0; },
	path_readlink: () => { return 0; },
	path_remove_directory: () => { return 0; },
	path_rename: () => { return 0; },
	path_symlink: () => { return 0; },
	path_unlink_file: () => { return 0; },
	poll_oneoff: () => { return 0; },
	proc_exit: () => { return 0; },
	sched_yield: () => { return 0; },
	random_get: () => { return 0; },
	sock_accept: () => { return 0; },
	sock_recv: () => { return 0; },
	sock_send: () => { return 0; },
	sock_shutdown: () => { return 0; },
};

export default wasi;
